### ISSUE TITLE
weixin_token_string 验证失败

### ISSUE THREAD

**Issue by chenzhong** [lanrion/weixin_rails_middleware#35]
自动生成的config/initializers/weixin_rails_middleware.rb文件中，会有注释掉的两行：
 ```
config.weixin_token_string = '5065183751f7a25a73eca72f'
config.weixin_secret_string = 'FSaRWRZ-1NxVF4q8Wx9sK1YGV4o3yScr'
```
这里面的token是无法通过weixin验证的

**Comment by lanrion** [comment]
贴一下版本号、详情的错误日志、具体的weixin_rails_middleware.rb 配置。

**Comment by lanrion** [comment]
目前微信公众号，添加了消息加密模式，请详见：https://github.com/lanrion/weixin_rails_middleware/wiki/msg-encryption-decipher
