### ISSUE TITLE
转发多客服消息

### ISSUE THREAD

**Issue by OhCoder** [lanrion/weixin_rails_middleware#37]
在response_text_message方法里调用 reply_transfer_customer_service_message(@weixin_message.Content) 进行多客服消息转发，转发完之后微信公众号会自动回复一条系统消息，说“该公众号暂时无法提供服务，请稍候再试”。
貌似这个方法并没有自动结束response_text_message方法的调用。

**Comment by lanrion** [comment]
请贴出异常信息。

**Comment by OhCoder** [comment]
已经搞定了，如果需要微信自己调用分配多客服消息，reply_transfer_customer_service_message方法不需要加参，调用默认转到多客服。
这次回复好快，thanks！

**Comment by lanrion** [comment]
不太明白。解决了就好。
