### ISSUE TITLE
小视频消息

### ISSUE THREAD

**Issue by josephktcheung** [lanrion/weixin_rails_middleware#38]
微信接收普通消息api多了一种小视频消息，现在没法正确传递到server，会出现`ArgumentError (Unknown Weixin Message)`

    <xml>
    <ToUserName><![CDATA[toUser]]></ToUserName>
    <FromUserName><![CDATA[fromUser]]></FromUserName>
    <CreateTime>1357290913</CreateTime>
    <MsgType><![CDATA[shortvideo]]></MsgType>
    <MediaId><![CDATA[media_id]]></MediaId>
    <ThumbMediaId><![CDATA[thumb_media_id]]></ThumbMediaId>
    <MsgId>1234567890123456</MsgId>
    </xml>

**Comment by lanrion** [comment]
小视频消息，即微视频吧，属于新的消息类型，目前版本未支持。正在修复中。

**Comment by greatghoul** [comment]
:+1:
