### ISSUE TITLE
自动回复功能

### ISSUE THREAD

**Issue by Wangjiaji007** [lanrion/weixin_rails_middleware#41]
```
def response_text_message(options={})
      message = @weixin_public_account.find_autoreply_by(@keyword)
      reply_text_message(message) if message.present?
end
```

我希望如果没有message, 就不回复，但是会报错 ` weixin_controller_decorator.rb:8:in `reply' `

**Comment by lanrion** [comment]
微信不能发送空消息吧？

**Comment by lanrion** [comment]
> 2、微信服务器在五秒内收不到响应会断掉连接，并且重新发起请求，总共重试三次。假如服务器无法保证在五秒内处理并回复，可以直接回复空串，微信服务器不会对此作任何处理，并且不会发起重试

如果确实要避免，消息为空的时候，返回一个 nil 即：`reply_text_message(nil)`.

**Comment by Wangjiaji007** [comment]
假如服务器无法保证在五秒内处理并回复，必须做出下述回复，这样微信服务器才不会对此作任何处理，并且不会发起重试（这种情况下，可以使用客服消息接口进行异步回复），否则，将出现严重的错误提示。详见下面说明：
```
1、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）
2、直接回复success
```

微信官方的说明，就是接口至少返回空串，才能避免报错。

**Comment by lanrion** [comment]
你试一下。

**Comment by Wangjiaji007** [comment]
你的
```
def reply_text_message(from=nil, to=nil, content)
      message = TextReplyMessage.new
      message.FromUserName = from || @weixin_message.ToUserName
      message.ToUserName   = to   || @weixin_message.FromUserName
      message.Content      = content
      encrypt_message message.to_xml
    end
```
把这个写死了。能不能写个统一接口只要收到请求，至少返回success，或者0字节字符串。多谢

**Comment by lanrion** [comment]
你试过 `reply_text_message(nil)` 吗？

**Comment by Wangjiaji007** [comment]
试过，不行的。因为你那只是设置 ` message.Content      = nil`

**Comment by lanrion** [comment]
我是可以的哦。

**Comment by lanrion** [comment]
自动回复功能，是一个很常见的功能，如果这个需求都无法的话，这个issue应该早有人报了。

**Comment by Wangjiaji007** [comment]
不报service unavailable 么？ 如果是这样，那我再看下。

**Comment by lanrion** [comment]
你的需求是，微信用户发送关键字过来，如果你的数据库没有找到针对这个关键字设置的回复内容，则不回复。即：`message = @weixin_public_account.find_autoreply_by(@keyword)`，为了排除其他非此gem的错误，先将**非**weixin_rails_middleware生成的代码去除，然后再直接 `reply_text_message(nil)`，你会发现，你在公众号上发任何文本消息，都不会有回应。

**Comment by Wangjiaji007** [comment]
ok, 多谢

**Comment by Wangjiaji007** [comment]
```    
def response_text_message(options={})
      # message = @weixin_public_account.find_autoreply_by(@keyword)
      reply_text_message(nil)
    end
```

我的微信账号里返回的是 `Official account services unavailable. Try again lager`

**Comment by lanrion** [comment]
http://mp.weixin.qq.com/debug/cgi-bin/sandboxinfo?action=showinfo&t=sandbox/index

**Comment by elele** [comment]
我也是这样,reply_text_message(nil)  一直提示 该公众号暂时无法提供服务,请稍后再试.

**Comment by lanrion** [comment]
@elele 可否把你的账号上传一下？

**Comment by elele** [comment]
@lanrion 什么账号? 我临时修改了一下
 def reply
    if @keyword && @weixin_message.MsgType == 'text' && @keyword.to_s != '1'
      return render :text => ''
    end
    render xml: send("response_#{@weixin_message.MsgType}_message", {})
  end

因为自动回复都是返回 xml 结构的数据,不需要回复的地方,微信官方说明
1、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）
2、直接回复success

还是有很多的回调处理会出现  该公众号暂时无法提供服务,请稍后再试 这样的提示
比如扫描二维码关注,自动发送模版消息等. 希望能加上一个不回复的功能.

**Comment by smoothdvd** [comment]
我直接改成这样了:
```
def reply
    if (response = send("response_#{@weixin_message.MsgType}_message", {})).nil?
      render text: ''
    else
      render xml: response
    end
end
````
