### ISSUE TITLE
取消关注 报错 NoMethodError (undefined method `empty?' for true:TrueClass):

### ISSUE THREAD

**Issue by leebo** [lanrion/weixin_rails_middleware#42]
```
NoMethodError (undefined method `empty?' for true:TrueClass):
  rack (1.6.4) lib/rack/etag.rb:67:in `block in digest_body'
  actionpack (4.2.3) lib/action_dispatch/http/response.rb:97:in `each'
  actionpack (4.2.3) lib/action_dispatch/http/response.rb:97:in `each'
  actionpack (4.2.3) lib/action_dispatch/http/response.rb:52:in `each'
  actionpack (4.2.3) lib/action_dispatch/http/response.rb:361:in `each'
  rack (1.6.4) lib/rack/etag.rb:65:in `digest_body'
  rack (1.6.4) lib/rack/etag.rb:28:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.3) lib/web_console/middleware.rb:29:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/bobo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/bobo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/bobo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'


  Rendered /Users/bobo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_source.erb (2.7ms)
  Rendered /Users/bobo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.5ms)
  Rendered /Users/bobo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.8ms)
  Rendered /Users/bobo/.rvm/gems/ruby-2.2.2/gems/actionpack-4.2.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (46.3ms)
```

**Comment by lanrion** [comment]
报错代码并未涉及到 weixin_rails_middleware，请贴出你的这部分的实现代码。

**Comment by elele** [comment]
我也有这样的问题,rails 4.2 ruby 2.2.1

**Comment by lanrion** [comment]
@elele 贴出你的代码看看。

**Comment by elele** [comment]
# 取消关注
  def handle_unsubscribe_event
    Rails.logger.info("取消关注")
  end
这里没有修改过,只要取消关注,就会产生和上面一样的异常错误.

**Comment by lanrion** [comment]
@elele 可以把完整的错误信息贴上来吗？

**Comment by lanrion** [comment]
刚刚试了一下master的代码，并没有重现此错：https://github.com/lanrion/weixin_rails_middleware_example

**Comment by elele** [comment]
: Processing by WeixinRailsMiddleware::WeixinController#reply as */*
I, [2015-08-13T09:12:50.424979 #30721]  INFO -- :   Parameters: {"signature"=>"c9bbd87a5685dbef360b81fb2efc7e521effd18c", "timestamp"=>"1439428370", "nonce"=>"1192004527", "encrypt_type"=>"aes", "msg_signature"=>"8537f8d673907a49fc8d3abf1458fc3e0ae15090", "weixin_secret_key"=>"e5dcd6ef90a6d3ca70f81fb8dc3f2017f0b1c29d019f1af8e711d295ca8ebca1e50886a5a219"}
I, [2015-08-13T09:12:50.426702 #30721]  INFO -- : 你点击了: https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx7785e5d9553bcd84&redirect_uri=http%3A%2F%2Fweixin.51cheling.com%2Fweixin_auth&response_type=code&scope=snsapi_userinfo&state=weixin#wechat_redirect
I, [2015-08-13T09:12:50.427206 #30721]  INFO -- : Completed 200 OK in 2ms (Views: 0.1ms | ActiveRecord: 0.0ms)
E, [2015-08-13T09:12:50.441939 #30721] ERROR -- : ** [Airbrake] Failure: Net::HTTPNotFound
D, [2015-08-13T09:12:50.442069 #30721] DEBUG -- : ** [Airbrake] Environment Info: [Ruby: 2.2.1] [Rails: 4.2.1] [Env: production]
D, [2015-08-13T09:12:50.442208 #30721] DEBUG -- : ** [Airbrake] Response from Airbrake:
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

D, [2015-08-13T09:12:50.442737 #30721] DEBUG -- : ** [Airbrake] Notice details:
  exception: undefined method `empty?' for true:TrueClass
  api_key: c5cba0804f8ada0c631c7e0b08151ce3
  backtrace: [PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/etag.rb:67:in `block in digest_body'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/http/response.rb:97:in `each'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/http/response.rb:97:in `each'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/http/response.rb:52:in `each'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/http/response.rb:362:in `each'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/etag.rb:65:in `digest_body'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/etag.rb:28:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/conditionalget.rb:38:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/head.rb:13:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/session/abstract/id.rb:225:in `context'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/session/abstract/id.rb:220:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/query_cache.rb:36:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:88:in `_run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:38:in `call_app'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `block in call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/rack/logger.rb:20:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/methodoverride.rb:22:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/runtime.rb:18:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/rack-1.6.2/lib/rack/sendfile.rb:113:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/engine.rb:518:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/railties-4.2.1/lib/rails/application.rb:164:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
[PROJECT_ROOT]/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'
  error_class: NoMethodError
  environment_name: production

**Comment by elele** [comment]
我改了一下,一定要返回个空,就没有错了
  # 点击菜单跳转链接时的事件推送
  def handle_view_event
    Rails.logger.info("你点击了: #{@keyword}")
    # 增加返回,就不会有异常
    reply_text_message("")
  end

**Comment by lanrion** [comment]
@elele 哟，原来是这样。

**Comment by ZPVIP** [comment]
只要在 reply_text_message 后面有任何语句都会出现这个错误。
