### ISSUE TITLE
如何在weixin_controller_decorator.rb文件以外使用reply方法

### ISSUE THREAD

**Issue by chenzhong** [lanrion/weixin_rails_middleware#46]
需要在weixin_controller_decorator.rb以外使用reply_news_message(articles)方法，是否只需要

``include WeixinRailsMiddleware::ReplyWeixinMessageHelper`` 即可？

目前在 一个class中 include过，但还是找不到该方法

```

class Notify

  include WeixinRailsMiddleware::ReplyWeixinMessageHelper

  def self.send_shop_message(articles)
    reply_news_message(articles)
  end


end
```

**Comment by lanrion** [comment]
没有这样子做过，如果要，需要实现`@weixin_adapter`，`@weixin_public_account`这两个属性。你可以试试。

**Comment by chenzhong** [comment]
OK， thanks！
