### ISSUE TITLE
Rails 5 貌似不支持。

### ISSUE THREAD

**Issue by Msms-NJ** [lanrion/weixin_rails_middleware#47]
报错：
verify_authenticity_token has not been defined

**Comment by lanrion** [comment]
有人在Rails 5试用了，我还想等5正式发布后，再做调试。
谢谢反馈，您能告诉我你详细的Rails的版本号吗？

**Comment by lanrion** [comment]
同时把详细的错误信息贴一次。

**Comment by Msms-NJ** [comment]
Rails 版本：Rails 5.0.0.beta3
`=> Booting Puma
=> Rails 5.0.0.beta3 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:641:in `block (2 levels) in skip_callback': Before process_action callback :verify_authenticity_token has not been defined (ArgumentError)
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:637:in `each'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:637:in `block in skip_callback'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:568:in `block in __update_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:566:in `reverse_each'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:566:in `__update_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:636:in `skip_callback'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:210:in `block (3 levels) in <module:ClassMethods>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:93:in `block in _insert_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:92:in `each'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:92:in `_insert_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:209:in `block (2 levels) in <module:ClassMethods>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/abstract_controller/callbacks.rb:216:in `block (2 levels) in <module:ClassMethods>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/weixin_rails_middleware-1.3.1/app/controllers/weixin_rails_middleware/weixin_controller.rb:5:in `<class:WeixinController>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/weixin_rails_middleware-1.3.1/app/controllers/weixin_rails_middleware/weixin_controller.rb:2:in `<module:WeixinRailsMiddleware>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/weixin_rails_middleware-1.3.1/app/controllers/weixin_rails_middleware/weixin_controller.rb:1:in `<top (required)>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:492:in `load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:492:in `block in load_file'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:682:in `new_constants_in'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:491:in `load_file'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:388:in `block in require_or_load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:37:in `block in load_interlock'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/concurrency/share_lock.rb:117:in `exclusive'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies/interlock.rb:11:in `loading'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:37:in `load_interlock'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:369:in `require_or_load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:529:in `load_missing_constant'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:212:in `const_missing'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:5:in `<top (required)>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `block in load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:296:in `load'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config/application.rb:14:in `block (2 levels) in <class:Application>'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config/application.rb:13:in `glob'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config/application.rb:13:in `block in <class:Application>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:396:in `instance_exec'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:396:in `block in make_lambda'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:546:in `catch'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:546:in `block in default_terminator'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:170:in `block in halting'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:454:in `block in call'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:454:in `each'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:454:in `call'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:750:in `_run_prepare_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/callbacks.rb:90:in `run_callbacks'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/reloader.rb:81:in `prepare!'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/actionpack-5.0.0.beta3/lib/action_dispatch/middleware/reloader.rb:53:in `prepare!'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:30:in `run'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/Msms/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/application.rb:350:in `initialize!'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config/environment.rb:5:in `<top (required)>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `block in require'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:268:in `load_dependency'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/activesupport-5.0.0.beta3/lib/active_support/dependencies.rb:302:in `require'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config.ru:3:in `block in <main>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `initialize'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config.ru:in `new'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/config.ru:in `<main>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in `build_app_and_options_from_config'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:58:in `app'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in `wrapped_app'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:136:in `log_to_stdout'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/server.rb:76:in `start'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/command.rb:20:in `run'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/railties-5.0.0.beta3/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/bin/rails:9:in `require'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/bin/rails:9:in `<top (required)>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/client/rails.rb:28:in `call'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from /Users/Msms/.rvm/gems/ruby-2.3.0@rails5.0/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/bin/spring:13:in `require'
	from /Users/Msms/Develop/workspace/wechatmanagement-plus/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
`

**Comment by lanrion** [comment]
已修复！请使用这个版本：

```ruby
gem 'weixin_rails_middleware', '~> 1.3', '>= 1.3.2'
```
