### ISSUE TITLE
貌似 rails 5 开始不鼓励使用 before_filter 了

### ISSUE THREAD

**Issue by Msms-NJ** [lanrion/weixin_rails_middleware#49]
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at ... .../app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at ... .../app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at ... .../app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:5)
DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead. (called from <top (required)> at ... .../app/decorators/controllers/weixin_rails_middleware/weixin_controller_decorator.rb:5)

**Comment by lanrion** [comment]
4就开始不再建议使用before_filter了，只不过是要兼容Rails 3而已。
现在Rails已经这么明显的WARNING了，那代码需要兼容一下了。

**Comment by lanrion** [comment]
有兴趣的话，可以发一个PR。
