### ISSUE TITLE
无法看到log

### ISSUE THREAD

**Issue by lzm420241** [lanrion/weixin_rails_middleware#50]
之前通过weixin_rails_middleware生成好的项目,由于出现问题然后将之前复制的一份项目放入之后,测试微信自动回复或者转客服回复都是无法看到log的

**Comment by lanrion** [comment]
需要看到什么log？

**Comment by lzm420241** [comment]
跳转到微信的信息还有返回的状态码啊

**Comment by lzm420241** [comment]
我今天再看的时候又出现了log,后来发现多客服功能中,如果客服在线,用户输入text文本直接转入多客服,而且会跳出`你点击了: http://mp.weixin.qq.com/s?__biz=MzA4Mzk2MzE5NQ==&mid=400974510&idx=1&sn=eb235f413c07ce821276185f008ba57d&scene=18#rd oMethodError (undefined method `empty?' for true:TrueClass)`,如果没有客服结果,log方面就没有问题

**Comment by lzm420241** [comment]
通过上面的推断,我觉得有再多客服开发上有一点逻辑上的不合理,比如说:如果用户发送一个text文本,那么当客服不在线的时候是可以转入response_text_message中处理,但是如果客服在线,那么text这个文本便不转入response_test_message,而是直接将text转入到多客服中的,如果说开发者希望将text在response_text_message中处理后再决定是否转入多客服是否更加合理?

**Comment by lanrion** [comment]
@lzm420241 这个要跟微信的反馈。如果已经接入了多客服，是不经过开发者服务器的。
