### ISSUE TITLE
Weixin signature NotMatch

### ISSUE THREAD

**Issue by Thomastar** [lanrion/weixin_rails_middleware#59]
单用户配置还是报错

**Comment by Thomastar** [comment]
已经配置好
config.encoding_aes_key = '<%= WeiXinUniqueToken.generate(generator: :hex, size: 22)[1..43] %>'
 config.app_id = "your app id"

**Comment by Thomastar** [comment]
若是我要选择明文，应该怎么弄

**Comment by Thomastar** [comment]
401 Unauthorized

**Comment by lanrion** [comment]
没有贴出任何有效的错误信息, 建议认真看一下: https://github.com/lanrion/weixin_rails_middleware/wiki/Getting-Start
