### ISSUE TITLE
NameError: uninitialized constant

### ISSUE THREAD

**Issue by Mamong** [lanrion/weixin_rails_middleware#63]
不知道为什么报这个错误，对rails还不太熟
环境ruby2.5.6
rails6.0.0
NameError: uninitialized constant Controllers::WeixinRailsMiddleware::WeixinControllerDecorator
Did you mean?  Controllers::WeixinRailsMiddleware::WeixinControllerDecorator

**Comment by sitoto** [comment]
感觉是rails版本升级到6.0后出现的问题.
我用5版本的时候,都还正常,今天升级到6.0后也出现这个了错误. @lanrion

**Comment by lanrion** [comment]
@sitoto Rails 6的controller加载机制改变了，代码要调整一下。我安排时间处理一下。

**Comment by lanrion** [comment]
已修复，请更新
`gem 'weixin_rails_middleware', '~>1.3.3'`
